### ISSUE TITLE
Usage from an external project

### ISSUE THREAD

**Issue by ebrehault** [guillotinaweb/ngx-schema-form#1]
@fbessou we start thinking about making a releasable bundle, so angular2-schema-form could be used as an external dependency in any regular project.
But we do not need a bundle here, we just need the .ts files, because the project will have its own webpack setup to compile everything anyway.

Nevertheless, we need to clean up our dependencies (some are declared as devDependencies but should not, like z-schema).

**Comment by ebrehault** [comment]
Few related issues:

- by using the master branch in my external project's package.json, `npm run build` is not executed, hence I do not get the right .js sources (it works with the dist branch https://github.com/plone/plone_client/blob/use-ng2-form/package.json#L81, where /dist folder is committed),
- I need to provide `FieldRegistryService` in my external app https://github.com/plone/plone_client/blob/use-ng2-form/src/components/app/app.component.ts#L33, that's not cool. Maybe that should be done by form.component directly (but will we be able to use ot from our external app?),
- I get a strange error:
    EXCEPTION: Error in ./StringField class StringField - inline template:4:224
    ORIGINAL EXCEPTION: No value accessor for ''
    Is anything missing (something else to provide like `FieldRegistryService`?) ?

**Comment by daniele-pecora** [comment]
Is this still a thing?

**Comment by ebrehault** [comment]
no it is not
