### ISSUE TITLE
removeItem() not updating view

### ISSUE THREAD

**Issue by mxchange** [guillotinaweb/ngx-schema-form#206]
`removeItem(i)` in `ArrayWidget` will delete an item, but the view doesn't update. 

The data is still correct when I submit the form, but the items will keep the same value as they had in that position. So if I have items 1, 2, 3, and remove 1, it wil show 1,2. instead of 2,3.

**Comment by WhileTrueEndWhile** [comment]
That's clearly a bug... If you remove the first element of two elements, the view and model do not match anymore. I have created the following array widget implementation which should solve the problem for me:

```
@Component({ templateUrl: "./my.array.widget.html" })
export class MyArrayWidget extends ArrayLayoutWidget {  
    public addItem(): void {
        const list = Array.from(JSON.parse(JSON.stringify(this.formProperty.value || [])));
        list.push(null);
        this.formProperty.setValue(list, false);
    }
    public removeItem(index: number): void {
        const list = Array.from(JSON.parse(JSON.stringify(this.formProperty.value || [])));
        list.splice(index, 1);
        this.formProperty.setValue(list, false);
    }
}
```

(*trackBy* was also removed from the template - I don't know what it does)
The default implementation should of course perform better...
