### ISSUE TITLE
Support for enum as combobox.

### ISSUE THREAD

**Issue by Domvel** [guillotinaweb/ngx-schema-form#221]
Support for properties with an enum array.

**Example**

```json
"version": {
  "type": "string",
  "enum": ["1.0", "1.1"]
}
```

**UI Solution**: 
A combobox (drop-down-menu) with all possible entries. 

**ngx-schema-form**: `^2.0.0-beta.3`,
**z-schma**: `^3.22.0`

**Comment by WhileTrueEndWhile** [comment]
I would look at the checkbox widget and implement a combo box myself using the bootstrap drop-down:

- https://github.com/makinacorpus/ngx-schema-form/blob/master/projects/schema-form/src/lib/defaultwidgets/checkbox/checkbox.widget.ts
- https://getbootstrap.com/docs/3.3/components/#dropdowns

**Comment by daniele-pecora** [comment]
This would allow an even simpler approach to design select element.
So I requested a merge with that.
