### ISSUE TITLE
[BUG] : Deleting any item from an ArrayLayoutWidget wrongfully pops the last inserted item.

### ISSUE THREAD

**Issue by AthanSoulis** [guillotinaweb/ngx-schema-form#235]
As the title says, deleting a random item from an ArrayLayoutWidget pops the last inserted item from the form.
Although in the model representation of the form the correct item is deleted from the array, on the actual form the last inserted array item is removed.

### Reproduction steps
In the [demo](http://makinacorpus.github.io/ngx-schema-form/dist/ngx-schema-form/) :

- Add 2 or more colors in the "Colors" array
- Remove whichever color array item you like (preferably not the last)
- Model representation is correct, the form is not

### Update

I have managed to pinpoint that the bug occurs when there is a `trackBy` method on the `ngFor` that is used to display the `formProperty.properties` of an ArrayLayoutWidget.
My guess would be that the DOM is not updated properly because if a `trackBy` method, that just returns the index of each item such as this :
````javascript
  trackByIndex(index: number, item: any) {
    return index;
}
````
from [here](https://github.com/makinacorpus/ngx-schema-form/blob/7c0a5df50abd119a5d37d4b816d1e0e198131af0/projects/schema-form/src/lib/defaultwidgets/array/array.widget.ts) is used, then the only DOM update will occur on the index that is missing (meaning the last one).

**Comment by WhileTrueEndWhile** [comment]
As long as there is no bugfix, the following workaround could help: https://github.com/makinacorpus/ngx-schema-form/issues/206

**Comment by AthanSoulis** [comment]
> As long as there is no bugfix, the following workaround could help: #206

Yup, its the same issue. I fixed mine by using this `trackBy` method:
````javascript
  trackByIndex(index: number, item: any) {
    return item;
  }
````
Namely, it returns the array item object reference as a tracking value for the `trackBy` method. When an item is deleted then the object reference is changed thus the `trackBy` method reports the change and both the view and the model are updated.

In [this](https://stackoverflow.com/questions/42108217/how-to-use-trackby-with-ngfor) accepted answer is explained in a few words how a `trackBy` method works.

Despite this, I do not know if returning the object reference is a good bugfix. What's your take on this?
