### ISSUE TITLE
Custom widget is not binded to schema model

### ISSUE THREAD

**Issue by flecce** [guillotinaweb/ngx-schema-form#248]
Hi,

I tried to create a new custom widget. The widget works but when I read the schema form model value, my widget value is not present.

Anyone has same problem?
Thanks in advance

**Comment by ebrehault** [comment]
You need to declare it in a registry:

```
import { MyStringWidget } from './mystring';

export class MyWidgetRegistry extends DefaultWidgetRegistry {
  constructor() {
    super();

    this.register('string',  MyStringWidget);
  }
}
```
then in your module, provide this registry and declare your widget entryComponent:
```
declarations: [MyStringWidget],
entryComponents: [MyStringWidget],
providers: [{provide: WidgetRegistry, useClass: MyWidgetRegistry}],

```

**Comment by flecce** [comment]
Yes I did. 
The widget is rendered and works as I expected. But the schema model is not binded.

**Comment by ebrehault** [comment]
could you paste your widget implementation in a [gist](https://gist.github.com/) so I can have a look?

**Comment by ebrehault** [comment]
I think you are overloading StringWidget on a bad way. As you just want to replace the html template, the TypeScript implementation must be just:
```
@Component({
  selector: 'app-text-widget',
  templateUrl: './text-widget.component.html',
  styleUrls: ['./text-widget.component.css']
})
export class TextWidgetComponent implements StringWidget {}
```

By declaring `formProperty;`, I am not sure but I think it will be considered as a `any`, while it should be a `FormControl`.
Just remove all those useless declarations, so you do not pollute the base class behavior.
And if you need to overload one of them, make sure to respect the base class typings and method signatures.

**Comment by flecce** [comment]
If I remove the useless declaration the compiler returns this message:

ERROR in shared/widgets/text-widget/text-widget.component.ts(9,14): error TS2720: Class 'TextWidgetComponent' incorrectly implements class 'StringWidget'. Did you mean to extend 'StringWidget' and inherit its members as a subclass?
  Property 'getInputType' is missing in type 'TextWidgetComponent'.

**Comment by ebrehault** [comment]
oh sorry I missed the most important!
You should not implement StringWidget, you must extend it:

```
export class TextWidgetComponent extends StringWidget {
```

**Comment by flecce** [comment]
Now it works!
Thanks

**Comment by ebrehault** [comment]
You're welcome :)
