### ISSUE TITLE
Property bindings first value is null

### ISSUE THREAD

**Issue by EricsG95** [guillotinaweb/ngx-schema-form#249]
I really like this custom property bindings, however I find that if it is used on 'select' component, there is a delay. On the first element that is being selected always null, only on the next value will be visible and what is being emited is actually the first value selected.

**Such as first event fires null, supposedly 1
And second event fires 1, supposedly 2.**

I have reproduced the issues on stackblitz, the values above will be printed in the developer console (F12). Thank you.

[Reproduced property binding issues](https://ngx-schema-playground.stackblitz.io)

If you have issues view the app above, please open it in Edge, else Chrome with 3rd party scripts enabled because of Stackblitz restrictions.

**Comment by ebrehault** [comment]
ok that's a bad one :)

@daniele-pecora, can you have a look whenever you have time?

**Comment by daniele-pecora** [comment]
Ok, I think to know what is meant

<img width="334" alt="null-first-value" src="https://user-images.githubusercontent.com/2026072/47390064-baeac300-d716-11e8-8dd8-201c3c126918.png">

I post here the editor version of the [Reproducing app link](https://stackblitz.com/edit/ngx-schema-playground)

**Comment by daniele-pecora** [comment]
For select elements you simply should use the `change` event instead of `input`.

```
...

'change': (event, formProperty: FormProperty) => {
          console.log('formProperty.value: ', formProperty.value);
        }

...
```

Try this out: https://stackblitz.com/edit/ngx-schema-playground-givbsn

**Comment by EricsG95** [comment]
Wow I see, thank you so much for your fast response. Is there anyway I can know what events are supported in property bindings. I really like this feature and find it very applicable to what I am working on now. Thank you so much for your hard work!

**Comment by daniele-pecora** [comment]
Any event you set in your `bindings` object will be passed to the `ElementRef`.
If it is supported by the view component it will be triggered.
