### ISSUE TITLE
Angular Pipe for Input Display

### ISSUE THREAD

**Issue by jackrvaughan** [guillotinaweb/ngx-schema-form#257]
I'd like to create a custom currency widget that displays commas with the Angular [DecimalPipe](https://angular.io/api/common/DecimalPipe), simple as this:

_1,000,000_

The [IntegerWidget](https://angular.io/api/common/DecimalPipe), which I'm trying to extend, does not have an [(ngModel)] to bind to in the template:

**IntegerWidget Template**
```
<div class="widget form-group">
	<label [attr.for]="id" class="horizontal control-label">
		{{ schema.title }}
	</label>
  <span *ngIf="schema.description" class="formHelp">{{schema.description}}</span>
	<input [attr.readonly]="schema.readOnly?true:null" [name]="name"
	class="text-widget integer-widget form-control" [formControl]="control"
	[attr.type]="'number'" [attr.min]="schema.minimum" [attr.max]="schema.maximum"
	[attr.placeholder]="schema.placeholder"
	[attr.maxLength]="schema.maxLength || null"
  [attr.minLength]="schema.minLength || null">
</div>
```

I tried to add something like this `[value] = "formProperty.value | number:'4.1-2'"`, but it didn't work. It seems that the values must be changed programmatically. 

How can we add a pipe transform in a custom widget?

Is there a way to do it in the template? Or do we need to do it in the component somehow like this: https://stackoverflow.com/questions/35144821/angular-use-pipes-in-services-and-components

Any help would be much appreciated!

**Comment by ebrehault** [comment]
I think `[value]="control.value | number:'4.1-2'"` should work, but make sure to remove `[attr.type]="'number'"` because it will raise a browser error.

**Comment by jackrvaughan** [comment]
Thanks @ebrehault, that works for adding the pipe!

Unfortunately, I can't remove the type number as I need to use the step functionality. I guess that's a limitation of the angular pipe though, not ngx-schema-form.

For now I'm just displaying the formatted number alongside the label:

```
	<label [attr.for]="id" class="horizontal control-label">
		{{ schema.title }} {{control.value | number:'1.0-2'}}
	</label>
```

Would be great to have an easy way of formatting the number input with commas, etc.

**Comment by ebrehault** [comment]
It is not an Angular limitation, it is just HTLM5 number type refusing non strict number value.
Maybe you can use a regular text type input and reimplement the step functionnality by yourself…

**Comment by jackrvaughan** [comment]
Finally got around to implementing this, if anyone else is interested in a custom widget to accommodate a difference between the displayed control value and the actual form value:

```import { Component, AfterViewInit } from '@angular/core';

import { Widget, FormProperty } from 'ngx-schema-form';
import { DecimalPipe } from '@angular/common';

@Component({
  selector: 'currency-widget',
  templateUrl: './currency-widget.component.html'
})
export class CurencyWidgetComponent extends Widget<FormProperty> implements AfterViewInit {
  constructor(
    private decimalPipe: DecimalPipe
  ){
    super();
  }

  ngAfterViewInit() {
    const control = this.control;
    this.formProperty.valueChanges.subscribe((value) => {
      if(value){
        let stringValue = '$' + this.decimalPipe.transform(value, '1.0-2')
        if (control.value !== stringValue) {
          control.setValue(stringValue, { emitEvent: false });
        }
      }
    });
    this.formProperty.errorsChanges.subscribe((errors) => {
      control.setErrors(errors, { emitEvent: true });
      const messages = (errors || [])
        .filter(e => {
          return e.path && e.path.slice(1) === this.formProperty.path;
        })
        .map(e => e.message);
      this.errorMessages = messages.filter((m, i) => messages.indexOf(m) === i);
    });
    control.valueChanges.subscribe((value) => {
      // remove $ and , then convert to Number
      let numberValue = Number(value.replace(/\$|,/g, ''))
      if (numberValue || numberValue === 0){
        let stringValue = '$' + this.decimalPipe.transform(numberValue, '1.0-2')
        if (control.value !== stringValue) {
          control.setValue(stringValue, { emitEvent: false });
        }
        this.formProperty.setValue(numberValue, false);
      } else {
        // some other non numerical character was added, don't change value
        let currentFormValue = this.formProperty.value
        let stringValue = '$' + this.decimalPipe.transform(currentFormValue, '1.0-2')
        control.setValue(stringValue, { emitEvent: false });
      }
    });
  }

}
