### ISSUE TITLE
Question: How to use Visible If with Array type

### ISSUE THREAD

**Issue by FathyV** [guillotinaweb/ngx-schema-form#258]
For example, I'm having an array contains some input fields. Now I want to add an new input fields outside the array and want  it to be display only when specific fields of the array has data. To make it works, I tried to use the `visibleIf` but I didn't success on making it show hide the new input fields properly. Is there away to achieve it? Am I using the wrong syntax or something?
Here is the example which I've created to describe the issue I'm facing.
https://stackblitz.com/edit/schema-form-array-visibleif

**Comment by daniele-pecora** [comment]
You are able to set a visibility binding path like
```
     "visibleIf" : {
           "peoples/0/name": ["lukas"]
     }
```
where `peoples` is you array and `0` points to the position of the items and `name` is a property of the array item at position 0.

## now the bad news
Although **ngx-schema-form** totally understands a path like this, 
the binding is processed at the target form-property at a time
where the array items are not yet known to the 
binding function `_bindVisibility` or simply don't exists yet.

**Comment by daniele-pecora** [comment]
## an idea

I discovered that when a form-property is created its visibility-binding is processed immediately.
So this assures that the visibility of the new created form-property is set right, 
but it misses to check if any other form-property visibility depends on this new form-property value.

To being able to update the visibility-binding of other form-property it requires an instance that is aware of all visibility dependencies between the form-property.

So when an instance of a form-property is created or destroyed this visibility-dependencies should be checked and updated.

**Comment by daniele-pecora** [comment]
So this issuw shpuld be marked as solved
