### ISSUE TITLE
Unused resp. overly specific peer dependencies

### ISSUE THREAD

**Issue by akloeber** [guillotinaweb/ngx-schema-form#260]
We migrated from angular2-schema-form to ngx-schema-form in order to get rid of peer dependency warnings under Angular 6.

Nevertheless there are still remaining warnings which suggest that the list of peer dependencies is not up-to-date.

The following `peerDependencies` are listed but they are not used/imported in the entire module:
```
"body-parser": "^1.15.1"
"methods": "^1.1.2"
"raw-loader": "0.5.1"
```

Moreover the following `peerDependencies` have a __specific__ version defined which contradicts the purpose of defining peer dependencies:
```
"core-js": "2.4.1",
"typescript": "2.3.4",
```
They should rather be defined as `core-js@^2.4.1` resp. `typescript@^2.3.4`.

__One minor point:__
The `z-schema`-dependency is used but it should either be converted into a real dependency or listed in `README.md` as simply running `npm install ngx-schema-form --save` is not sufficient for using the library (also see #214).

__Version:__ `ngx-schema-form@2.2.0-beta.1`

**Comment by ebrehault** [comment]
Correct. I am currently upgrading to ng7, so let me fix that at the same time.
Thanks!

**Comment by akloeber** [comment]
@ebrehault I already prepared a PR.

**Comment by ebrehault** [comment]
Cool thanks! (and merged by the way)

**Comment by akloeber** [comment]
@ebrehault In release 2.3.0 `body-parser` is a `peerDependency` again. Was that a mistake or is there any reason?

**Comment by akloeber** [comment]
@ebrehault Is ngx-schema-form no more compatibility with Angular 6? We are still on v6 and want to wait until v7 has matured as we had problems with early adoption of new Angular versions in the past. 
If it is compatible with both major versions of angular maybe a version range for the peerDependencies would be better, e.g. `"@angular/animations": ">=6 <=7"`.

**Comment by ebrehault** [comment]
> In release 2.3.0 body-parser is a peerDependency again. Was that a mistake or is there any reason?

complete mistake… sorry!

> Is ngx-schema-form no more compatible with Angular 6?

it is compliant (I have made no change in the implementation to support ng 7), so yes let's fix the package.json
