### ISSUE TITLE
Types missing in public API after migration to `ngx-schema-form`

### ISSUE THREAD

**Issue by akloeber** [guillotinaweb/ngx-schema-form#262]
After upgrating from `angular2-schema-form` to `ngx-schema-form` some types/classes are missing in the public API.

`Widget<T extends FormProperty>` is part of the public API but `FormProperty` needs to be imported like this:

```
import {FormProperty} from 'ngx-schema-form/lib/model/formproperty';
```
instead of
```
import {FormProperty} from 'ngx-schema-form';
```

The same goes for `ArrayProperty` which we use for defining our own `class ArrayAdapterComponent extends Widget<ArrayProperty>`

Furthermore we are using the following components which are also missing:
- `FormPropertyFactory`
- `SchemaPreprocessor`
- `WidgetFactory`
- `TerminatorService`

Right now - because of minification - we need to import them via:
```js
import {
  ɵd as FormPropertyFactory,
  ɵb as SchemaPreprocessor,
  ɵc as WidgetFactory,
  ɵe as TerminatorService,
} from 'ngx-schema-form';
```

**Comment by ebrehault** [comment]
oh, I was not aware, that's pretty bad indeed
