### ISSUE TITLE
Keyword 'required' is expected to be of type 'array'

### ISSUE THREAD

**Issue by JohannesRudolph** [guillotinaweb/ngx-schema-form#263]
After upgrading to 2.3.0 we see the following error for one of our schemas: 

```json
{"code":"KEYWORD_TYPE_EXPECTED","params":["required","array"],"message":"Keyword 'required' is expected to be of type 'array'","path":"#/properties/costTypeValue","schemaId":null}]"
```

I think this may come from the following change: https://github.com/guillotinaweb/ngx-schema-form/commit/7f254f1eb96261e1c2325f017eb15c99f506d2cd
 where the schame preprocessor adds an apparently invalid `.required`  `jsonSchema.properties[fieldId].required = true` to my schema object. This causes a "schema validation error" (i.e. the schema itself appears to be invalid?). 

My schema looks like this:

```json
{
  "$id" : "https://schemas.meshcloud.io/project-tags",
  "type" : "object",
  "properties" : {
    "costTypeValue" : {
      "$id" : "/properties/costTypeValue",
      "type" : "string",
      "title" : "Cost Type Value",
      "default" : "23432",
      "maxLength" : 191,
      "pattern" : ".+",
      "examples" : [ "123" ]
    },

  "required" : [ "costTypeValue" ]
}```

**Comment by dmcdaniel12** [comment]
@JohannesRudolph We are seeing a very similar issue as well

**Comment by enavarro222** [comment]
I'll really appreciate if you can release a new version with this fix !

The last version 2.3 is unusable for me without this fix, however I strongly need this new version (especially for the class FormPropertyFactory and FormProperty exposed in public API).

Thanks for all your great job on this library !

**Comment by ebrehault** [comment]
Done in version 2.3.2

**Comment by enavarro222** [comment]
@ebrehault thanks a lot !
