### ISSUE TITLE
Custom widget is not binding to schema model

### ISSUE THREAD

**Issue by sammaphey** [guillotinaweb/ngx-schema-form#270]
Related to #248, I seem to be running into the same problem though I am not sure what I could be doing wrong. 

Relevant files: 
`image-widget.ts`
```import { Component } from '@angular/core';
import { StringWidget } from 'ngx-schema-form';

@Component({
  selector: 'app-image-widget',
  templateUrl: './image-widget.component.html'
})
export class ImageWidgetComponent extends StringWidget {}
```

`image-widget.component.html`
```<div class="row">
    <div class="col-md-8">
        <input class="form-control" [name]="name" placeholder="Enter uri..." />
    </div>
    <div class="col-md-4">
        <button class="btn btn-primary" (click)="selectFile()">Select file</button>
    </div>
</div>
```

`widget-registry.ts`
```import { ImageWidgetComponent } from './image-widget/image-widget.component';
import { DefaultWidgetRegistry } from 'ngx-schema-form';

export class CustomWidgetRegistry extends DefaultWidgetRegistry {
  constructor() {
    super();

    this.register('image',  ImageWidgetComponent);
  }
}
```

Relevant schema: 
```{
  "email": {
    "type": "string",
    "description": "email",
    "format": "email"
  },
  "password": {
    "type": "string",
    "description": "Password"
  },
  "rememberMe": {
    "type": "boolean",
    "default": false,
    "description": "Remember me"
  },
  "image": {
    "type": "string",
    "description": "Image",
    "widget": "image"
  }
}
```

The widget shows as expected but when I edit the field for image it never saves to the schema

**Comment by tjchambers32** [comment]
I think in your template file it should be 

`<div>
    <div class="col-md-8">
        <input class="form-control" [formControl]="control" [name]="name" placeholder="Enter uri..." />
    </div>
    <div class="col-md-4">
        <button class="btn btn-primary" (click)="selectFile()">Select file</button>
    </div>
</div>
`

Then in your app.module.ts you'll also need to import the ReactiveFormsModule. Have a look through the string.widget.ts file to see how it was implemented, yours will be similar.

https://github.com/guillotinaweb/ngx-schema-form/blob/master/projects/schema-form/src/lib/defaultwidgets/string/string.widget.ts

**Comment by sammaphey** [comment]
Thank you travis!
