### ISSUE TITLE
Add custom class to div

### ISSUE THREAD

**Issue by Iquebal** [guillotinaweb/ngx-schema-form#279]
Add custom class to div and add our own css style to any div.

**Comment by fincha** [comment]
I am not really a contributor to this project, but issues like this will probably be closed soon. What is this? Help request, feature request or storry telling about your last code session?!

**Comment by daniele-pecora** [comment]
If providing a custom style and overriding the css selectors is not an option for you I would consider creating your own widget library.

For an example of creating a custom widget library head over to [this stackblitz example](https://stackblitz.com/edit/ngx-schema-form-customs)
