### ISSUE TITLE
how to create customer widget without input

### ISSUE THREAD

**Issue by JianhuisHuang** [guillotinaweb/ngx-schema-form#280]
how to create customer widget without input?example: ngx-cropper,etc.thanks

**Comment by daniele-pecora** [comment]
**Layout widget**   
To create a custom widget without any value binding you have tp create a so called "Layout widget".   
This can be simply done by extending `ObjectLayoutWidget`.   
Head over to this [Stackblitz example](https://stackblitz.com/edit/ngx-schema-form-customs) and take a look at the widget "**paragraph**".  
The widget "paragraph" does only render an HTML **<p>** tag.

**Comment by daniele-pecora** [comment]
Closing this, since above answer should be sufficient
