### ISSUE TITLE
Select is not disabled in readOnly mode

### ISSUE THREAD

**Issue by cardioprint** [guillotinaweb/ngx-schema-form#287]
Hi guys. 
First of all, many thanks for this awesome library!

There is a **bug**: select widget is not disabled by ```[disabled]``` property in readOnly mode.
Here is minimal [Stackblitz example](https://stackblitz.com/edit/angular-jtzsuy).

Possible solution: 
replace ```[disabled]="schema.readOnly"``` with ```[attr.disabled]="schema.readOnly"```. It fixes the issue but I'm not sure how it could affect another functionality. 

Here is [commit](https://github.com/guillotinaweb/ngx-schema-form/pull/266/commits/7591d9ebec1cb182f4b112ea6503c6b6c7038925) where ```[attr.disabled]``` was replaced with ```[disabled]``` #266

**Comment by daniele-pecora** [comment]
Would you like to make a pull request to this?

**Comment by cardioprint** [comment]
Guys, could you please make a release? I would be very glad to have this fix in my project. Thanks in advance!

**Comment by daniele-pecora** [comment]
You are right, a new PR wont solve this issue.

Please head over to https://github.com/guillotinaweb/ngx-schema-form/issues/306 to get an impression of the whole problem here.

I think we do really need the both states: `readOnly` and `disabled`.

**Comment by daniele-pecora** [comment]
I digged a bit deeper and came to the opinion that this is a miscoception in `@angular/forms` `ReactiveForms`  :  https://github.com/angular/angular/issues/11271
