### ISSUE TITLE
Angular 8: __evaluateVisibilityIf() cannot read the property 'indexOf' of NULL

### ISSUE THREAD

**Issue by tqduy** [guillotinaweb/ngx-schema-form#305]
Hi everyone, 
I am facing the issue when upgrading from angular **5.1.0** to **8**
I change from `angular2-schema-form` to `ngx-schema-form` and I face this issue when parsing the `VisibilityIf` condition at function `__evaluateVisibilityIf()`

![image](https://user-images.githubusercontent.com/11729162/64601330-f487f380-d3e6-11e9-94cd-feaa494542e6.png)

My `value` is not '' but null and cause the exception
![image](https://user-images.githubusercontent.com/11729162/64601468-30bb5400-d3e7-11e9-9376-5369067d650d.png)

Here is the json, I just show the screenshot of structure because the real json is too long 
![image](https://user-images.githubusercontent.com/11729162/64602569-3c0f7f00-d3e9-11e9-8826-2a7820f6628f.png)

Can anyone help me with this case?
Thank you.

**Comment by daniele-pecora** [comment]
This is already fixed in #298

Duplicate #304
Waiting for a new release.
@ebrehault could you?

**Comment by ebrehault** [comment]
Done
