### ISSUE TITLE
ngx-schema-form does not support es5 (IE11)

### ISSUE THREAD

**Issue by tqduy** [guillotinaweb/ngx-schema-form#310]
Hello everyone,
I am having an issue when using ngx-schema-form on Angular 8
My project does not work on IE11 browser, here is the error:
![image](https://user-images.githubusercontent.com/11729162/66550173-05a35c00-eb6f-11e9-8746-a9af64ecc4bd.png)

As I can see that the  The ngx-schema-form didn't support IE11, it works for ES6 only:
![image](https://user-images.githubusercontent.com/11729162/66550213-1bb11c80-eb6f-11e9-929f-3057e27778e6.png)

and IE11 is not included in browser list:
![image](https://user-images.githubusercontent.com/11729162/66550260-371c2780-eb6f-11e9-9c1a-8a1836627dbb.png)

Is there any solution for me to use it on both modern and old browser? 
Note: Other browsers work like a charm, even Edge.
Thank you.

**Comment by ebrehault** [comment]
Hi!

Sorry but we do not plan to invest time in supporting IE11.
Nevertheless if you want to give it a try, you can try to change the tsconfig target and see how it goes.
