### ISSUE TITLE
visibleIf with buttons

### ISSUE THREAD

**Issue by AviFix** [guillotinaweb/ngx-schema-form#320]
Hi,

visibleIf works fine with form fields, but I couldn't get it to work with buttons.

I want a button to show only if for example the user's age field is set to 18.

Thanks

**Comment by AviFix** [comment]
Anyone?

**Comment by daniele-pecora** [comment]
@AviFix  This feature is not yet available, but my come in future. For me it sound really usefull.  

All you can do for now is to switch between 2 widgets where one contains an action button and the other not.
