### ISSUE TITLE
Custom Button Widget unable to trigger form [actions].

### ISSUE THREAD

**Issue by ying8599** [guillotinaweb/ngx-schema-form#321]
I have created a custom button and also an action (followed the read me - Actions and buttons guide).

It is able to render the custom button but unable to trigger event in Myactions.

customButtonWidget
html :
```
<button 
mat-stroked-button color="{{button.color}}" id="{{button.id}}">{{button.label}}</button>
```

AppComponent
```
  myActions = {
    alert: (property) => { alert(JSON.stringify(property.value)); },
    reset: (property) => { property.reset(); }
  };
```

**Comment by WhileTrueEndWhile** [comment]
Try to use regular angular event handling. Referring the README `myActions` is bound to  `<sf-form/>` like `[actions]="myActions"`. But you are **not** using `<sf-form/>`. Something like `(click)="onClick($event)"` with a corresponding `onClick` TS method should be sufficient.

**Comment by ying8599** [comment]
Thanks for the response.
I have used another method to do the dynamic from.
