### ISSUE TITLE
visibleIf "allOf" Edge case BUG

### ISSUE THREAD

**Issue by AviFix** [guillotinaweb/ngx-schema-form#329]
Hi,

In the following schema follow in the exact order:
1: Set the "Last name" to BBB
2: set the age to 15
The "First name" field will appear as expected.
3: change "Last name" to AAA
The "First name" Still exists (It shouldn't).

```
mySchema =
    {
      'properties': {
        'age': {
          'id': 'age',
          'name': 'age',
          'title': 'Age',
          'type': 'string',
          'widget': {'id': 'string'}
        },
        'firstName': {
          'id': 'firstName',
          'name': 'firstName',
          'title': 'First Name',
          'type': 'string',
          'visibleIfOperator': 'and',
          'widget': {'id': 'string'},
          'visibleIf': {'allOf': [{'lastName': 'aaa'}, {'age': 15}]}
        },
        'lastName': {
          'id': 'lastName',
          'name': 'lastName',
          'title': 'Last Name',
          'type': 'string',
          'widget': {'id': 'select'},
          'oneOf': [
            {
              'description': 'AAA',
              'enum': [
                'aaa'
              ],
            },
            {
              'description': 'BBB',
              'enum': [
                'bbb'
              ],
            }]
        }
      }
    };
````

**Comment by daniele-pecora** [comment]
I have got this example here on stackblitzt where I put you schema in:
https://stackblitz.com/edit/schema-form-array-visibleif-binding-issue329

It's working fine on Microsoft Edge and Chrome

**Comment by AviFix** [comment]
Hi @daniele-pecora,

in your example do the following steps:

- set the last name to BBB
- set the age to 15
- Click on the last name again (to focus) but do not change your selection
- change the age and the first name will still be showing
![aaa](https://user-images.githubusercontent.com/3835504/84481307-8e463f00-ac9e-11ea-939f-fc2447313a45.gif)

**Comment by daniele-pecora** [comment]
@AviFix 
[Update demo on stackblitz with latest ngx-schema-form](https://stackblitz.com/edit/schema-form-array-visibleif-binding-issue329):
https://stackblitz.com/edit/schema-form-array-visibleif-binding-issue329

![visibleIf-issue-329-solved](https://user-images.githubusercontent.com/2026072/90796614-d2456800-e30f-11ea-876e-565b889605e1.gif)
