### ISSUE TITLE
visibleIf stopped working in 2.5.2

### ISSUE THREAD

**Issue by petrce** [guillotinaweb/ngx-schema-form#331]
Hi it looks like this change broken visibleIf functionality:
https://github.com/guillotinaweb/ngx-schema-form/commit/9574ec45d8ac89ecca2a8976df7d575f5085e111

based on the documentation we were using:
```        
// Declare that this field must be displayed only if registerNewsletter is true
        "visibleIf": {
          "registerNewsletter": [true]
        }
```      
https://github.com/guillotinaweb/ngx-schema-form#conditional-fields

this stopped working

**Comment by bennmapes** [comment]
I'm getting the same issue, it still works for string values but not for booleans.
