### ISSUE TITLE
NPM Package Page Readme Not Found

### ISSUE THREAD

**Issue by chuckle123** [guillotinaweb/ngx-schema-form#355]
[https://www.npmjs.com/package/ngx-schema-form](https://www.npmjs.com/package/ngx-schema-form)

![image](https://user-images.githubusercontent.com/10111341/87684606-71df6b80-c750-11ea-8d7d-f0e4a6725b76.png)

Just a heads up.
Awesome package.

Cam

**Comment by ebrehault** [comment]
Ooops…
Thanks!
