### ISSUE TITLE
Add support for Angular 11

### ISSUE THREAD

**Issue by Jelledb** [guillotinaweb/ngx-schema-form#382]
It would be great if you guys could add official support for Angular 11.

This ensures that users of the library can trust that the library works with Angular 11.

I did some manual testing with this library and Angular 11 and everything seems to work fine, but it would be great to get rid of the peer dependencies warning:

```
warning " > ngx-schema-form@2.5.8" has incorrect peer dependency "@angular/common@^9.0.4".
warning " > ngx-schema-form@2.5.8" has incorrect peer dependency "@angular/core@^9.0.4".
warning " > ngx-schema-form@2.5.8" has incorrect peer dependency "@angular/forms@^9.0.4".
warning " > ngx-schema-form@2.5.8" has incorrect peer dependency "@angular/platform-browser@^9.0.4".
```

**Comment by ebrehault** [comment]
Fixed, 2.6.0 is released and provides Angular 11 support.
