### ISSUE TITLE
Proposal: allow to use nullable union type not only for oneOf case

### ISSUE THREAD

**Issue by iperevozchikov** [guillotinaweb/ngx-schema-form#412]
Hi, @ebrehault!

A few monthes ago I was implemented #397  proposal to support nullable union types. And everything was good until yesterday while we not decided to move our selects to new type of widget like autocomplete and without using of oneOf property. 
But constraint that I implemented in proposal doesn't allow to use this.

Another problem from my previous solution is buggy types in Schema type definition.

So in that issue I want to do the next job:
1. Remove constraint of using only with oneOf
2. Add null type as new FieldType
3. Add NullProperty, which will return null as fallback value
4. Update StringProperty to allow to return null as fallback value if property has nullable union.
5. Fix types in ISchema

**Comment by iperevozchikov** [comment]
PR: #413

**Comment by iperevozchikov** [comment]
@ebrehault I see that you merged PR thanks! But still have a question about npm - could you publish new version of library there with my changes?

**Comment by ebrehault** [comment]
Hi @iperevozchikov !
Yes sure, version 2.6.7 is now on npm.
By the way, for your future PRs, if you update the version number in `projects/schema-form/package.json` and add an entry in CHANGELOG.md, then GitHub Actions will automatically tag and publish to npm at the time the PR is merge :)

**Comment by ebrehault** [comment]
example here: https://github.com/guillotinaweb/ngx-schema-form/commit/426af24763de06c4386e77add873281be407f5e3

**Comment by iperevozchikov** [comment]
Got it, thanks for advice!
