### ISSUE TITLE
Parent container for all the form actions

### ISSUE THREAD

**Issue by krishna217** [guillotinaweb/ngx-schema-form#424]
Is it possible to add a parent container for all the form actions to make it easier to format all buttons ?

**Comment by ebrehault** [comment]
I do not see an easy way to create a container for the buttons.
If you just need to format the buttons, you can use `sf-button-widget ::ng-deep button` as CSS selector.

**Comment by krishna217** [comment]
Thanks. But it would have been nice to have something similar to `sf-widget-chooser` for form actions

**Comment by daniele-pecora** [comment]
@krishna217 
As far as I see all action-buttons have a parent element `sf-form-element-action`.
<img width="649" alt="action-buttons" src="https://user-images.githubusercontent.com/2026072/149090576-467b4ae5-17bf-43a4-aabb-a72bf928ccfd.png">
