### ISSUE TITLE
when adding my angular 14.0.6 project  > npm install ngx-schema-form --save

### ISSUE THREAD

**Issue by brayanmf** [guillotinaweb/ngx-schema-form#443]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: inspecciones@0.0.0       
npm ERR! Found: @angular/common@14.0.6
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.0.6" from the root project        
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.1.1" from ngx-schema-form@2.7.1
npm ERR! node_modules/ngx-schema-form
npm ERR!   ngx-schema-form@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\USUARIO\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USUARIO\AppData\Local\npm-cache\_logs\2022-07-14T18_48_32_317Z-debug-0.log

**Comment by ebrehault** [comment]
Fixed in version 2.8.0 (providing Angular 14 compliancy)

**Comment by krishna217** [comment]
@ebrehault still the peer dependencies say `v13` https://github.com/guillotinaweb/ngx-schema-form/blob/master/projects/schema-form/package.json#L30

**Comment by ebrehault** [comment]
oh right! let me fix that

**Comment by ebrehault** [comment]
fixed in 2.8.1
