### ISSUE TITLE
Intergration with 3rd party widget (e.g. primeng, material)

### ISSUE THREAD

**Issue by kovax** [guillotinaweb/ngx-schema-form#45]
Do you have any means/plans to use primeng widgets?

I am planning to rewrite a java swing ui, which uses xml schema to build its forms. I have chosen angular 2 for the development, and your project combined with primeng looks to me the best solution.

**Comment by daniele-pecora** [comment]
I'd like to reopen this since I do have plans to provide exactly this two libraries this year 2019.
So whish me luck that it wents well.
