### ISSUE TITLE
Compatibility with angular 16

### ISSUE THREAD

**Issue by Wooshaah** [guillotinaweb/ngx-schema-form#474]
It's currently not possible (without using --force) to update an angular 15 app to angular 16 due to incompatible peer dependencies.

![image](https://user-images.githubusercontent.com/26672237/236125279-b5c5ccc8-d1c0-4c9c-a37e-e6ad56f106cb.png)

**Comment by ebrehault** [comment]
I have just tried to upgrade but it failed. I think it is still a bit early. I'll try again when Angular 16.0.1 is out (ping me if I forget).

**Comment by ebrehault** [comment]
@Wooshaah version 2.10.0 has just beel released and provides support for Angular 16
