### ISSUE TITLE
upgrade to Angular 17

### ISSUE THREAD

**Issue by Wooshaah** [guillotinaweb/ngx-schema-form#483]
Hello,

When updating to angular from 16 to 17 (`ng update @angular/cli@^17 @angular/core@^17`) we are facing incompatible peer dependencies with this package.

`Package "ngx-schema-form" has an incompatible peer dependency to "zone.js" (requires "~0.13.0", would install "0.14.2").`

the @angular/core package seems to have a dependency on version `~0.14.0`.
see: https://github.com/angular/angular/blob/1e87ce2de29950aacf9c1ce4d53206174a0cfea1/packages/core/package.json

Would it be possible to add angular 17 support?

Thanks!

**Comment by ebrehault** [comment]
Definitely.
Let me update the package.

**Comment by ebrehault** [comment]
Fixed in version 2.11.0
