### ISSUE TITLE
Getting error when installing

### ISSUE THREAD

**Issue by anupamarachuri** [guillotinaweb/ngx-schema-form#9]
22181 verbose cwd C:\Users\Nirupama\Downloads\angular2-seed-master\angular2-seed-master
22182 error Windows_NT 10.0.10586
22183 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "angular2-schema-form" "--save-dev"
22184 error node v4.4.7
22185 error npm  v2.15.8
22186 error code EPEERINVALID
22187 error peerinvalid The package @angular/common@2.0.0-rc.5 does not satisfy its siblings' peerDependencies requirements!
22187 error peerinvalid Peer @angular/forms@0.3.0 wants @angular/common@^2.0.0-rc.5
22187 error peerinvalid Peer @angular/platform-browser@2.0.0-rc.5 wants @angular/common@^2.0.0-rc.5
22187 error peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.5 wants @angular/common@^2.0.0-rc.5
22187 error peerinvalid Peer @angular/router@3.0.0-rc.1 wants @angular/common@^2.0.0-rc.5
22187 error peerinvalid Peer @angular/platform-server@2.0.0-rc.4 wants @angular/common@^2.0.0-rc.4
22187 error peerinvalid Peer angular2-schema-form@1.0.0-alpha.16 wants @angular/common@2.0.0-rc.4
22188 verbose exit [ 1, true ]

Please suggest!

**Comment by fbessou** [comment]
It should work fine with the latest version of the package.

**Comment by rishabmehra** [comment]
Try with angular2-cli and it will work

**Comment by daniele-pecora** [comment]
This issue may be closed since it is related to angular2
