### ISSUE TITLE
How to use setValue() to change an already rendered form

### ISSUE THREAD

**Issue by mbanduk** [guillotinaweb/ngx-schema-form#98]
How to get the reference to a given form so I can call `setValue()`

Is there an `angular2-schema-form` default way of doing that?

**Comment by mbanduk** [comment]
For now Im just updating the model. But wondering if there's a better way of doing that...

```
const newModel = Object.assign({}, this.gamePlayerModel, updatedValues)
this.gamePlayerModel = newModel
```

**Comment by ebrehault** [comment]
Updating the model is fine.
